modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="mxl_inf" #mandatory
version="1.16.4-1.0.2" #mandatory
displayName="Infinitum Mod" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/XenonNeko/Minecraft-1.16.4-Forge-InfinitumMod" #optional
logoFile="logo.png" #optional
credits="Thanks to TechnoVision and TurtyWurty for your tutorials!" #optional
authors="Xenon Neko" #optional
description='''
Have you ever wanted a challenge in Minecraft?
No?
Well why not try Infinitum!
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
